name: Call Reusable Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  call-code-check:
    uses: ./.github/workflows/code-check.yaml
    with:
      python-version: '3.10'
  call-ci:
    needs: call-code-check
    uses: ./.github/workflows/unittest.yaml
    with:
      python-version: '3.10'

  generate-third_party_licenses:

    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions: # ここを追加
      contents: write
      pull-requests: write
    needs: call-code-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
          poetry add pip-licenses
      - name: Generate third-party licenses
        run: |
          poetry run pip-licenses --format=markdown --output-file=third_party_licenses.md
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          if [ -n "$(git status --porcelain third_party_licenses.md)" ]; then
            git add third_party_licenses.md
            git commit -m "Update third-party licenses"
            git push
          else
            echo "No changes in third_party_licenses.md. Skipping commit and push."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

