name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  code-check:
    permissions:
      contents: read
    uses: S-mishina/reusable-workflows/.github/workflows/python-lint.yml@main
    with:
      python-version: "3.10"

  test:
    permissions:
      contents: read
    needs: code-check
    uses: S-mishina/reusable-workflows/.github/workflows/python-test-poetry.yml@main
    with:
      python-version: "3.10"
      pythonpath: src
