name: Publish to PyPI

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry

      - name: Build package
        run: |
          poetry build

      - name: Configure Poetry
        run: |
          poetry config repositories.h_processor https://upload.pypi.org/legacy/
          poetry config http-basic.h_processor __token__ ${{ secrets.PIP_SECRET }}
      - name: Publish to PyPI
        env:
          API_TOKEN: ${{ secrets.PIP_SECRET }}
        run: |
            poetry publish --repository h_processor -u __token__ -p $API_TOKEN
